### ISSUE TITLE
[Bug]: Values that shouldn't kill with damage library kill on servers

### ISSUE THREAD

**Issue by SpluoSplatus** [Smithed-MC/Libraries#15]
**Describe the bug**
On a Minecraft server (specifically the one I used, aternos)  low values put into the smithed.damage score and then running the function `#smithed.damage:entity/apply/armor` instakills the player. Additionally, it gives the death message "Splatus fell out of the world" even though the damage from the library normally doesn't produce any death message.

**To Reproduce**
1.  Setup an aternos server with the Smithed damage library datapack installed
2. Start and join the server
3. Run the command `/scoreboard players set @s smithed.damage 1`
4. Run the command `/function #smithed.damage:entity/apply/armor`
5. Observe Behavior; player gets instakilled even though the damage value is low

**Expected behavior**
Damage should have been 1/2 heart of damage

**Screenshots and/or Videos**

**Details**
**Aternos Vanilla Server 1.19**/**Fabric 1.19 Client**
**Platform**: Fabric
**Version**: v0.0.4

**Additional context**
Works fine in singleplayer and does not instakill

**Comment by RitikShah** [comment]
Already fixed in #14, not sure how this bug manifested itself earlier though.
