### ISSUE TITLE
[Feature]: Add a function to deal pure damage IN the [...]/apply/ folder

### ISSUE THREAD

**Issue by FunkyToc** [Smithed-MC/Libraries#23]
**Which library (or new library) would this feature fit into**
damage

**Describe the feature you wish and why you need it**
Add a function to deal pure damage IN the [...]/apply/ folder
Simply make it clearer that the apply.mcfunction is pure damage
Also contains apply functions in one folder for easier pack comprehension

**Do you have any code examples, partial implementations, etc**
Add a function to deal pure damage IN the [...]/apply/ folder

**Additional context**
I may push it, but it's about a 10s feature

![image](https://user-images.githubusercontent.com/29950285/214535092-ab21f60d-9755-47ee-beff-bdf1245afd4f.png)

**Comment by RitikShah** [comment]
Closing since /damage is a command. smithed.damage will not make it to 1.20.
