### ISSUE TITLE
[Bug]: Damage sound not happening 1.19.3

### ISSUE THREAD

**Issue by FunkyToc** [Smithed-MC/Libraries#24]
**Describe the bug**

**To Reproduce**
1. `/scoreboard players set @s smithed.damage 3`
2. `function smithed.damage:impl/entity/apply`
3. Listen behavior... no sound

**Expected behavior**
Take damage as player should display a sound, at least @s
Could be an option to chose before applying damage in apply.mcfunction

**Details**
**Client**: 1.19.3
**Platform**: Vanilla
**Mods**: /
**Other Packs**: /
**Version**: v0.0.4

**Comment by RitikShah** [comment]
Closing since /damage is a command. smithed.damage will not make it to 1.20.
