### ISSUE TITLE
[Feature]: Damage pool to fix the 1-tick-immunity

### ISSUE THREAD

**Issue by FunkyToc** [Smithed-MC/Libraries#25]
**Which library (or new library) would this feature fit into**
Damage

**Describe the feature you wish and why you need it**
Current version do not handle multiple damage in the same tick. 
`scoreboard players add @s smithed.damage 2`
`function smithed.damage:impl/entity/apply`
`scoreboard players add @s smithed.damage 2`
`function smithed.damage:impl/entity/apply`
The second damage will vanish, due to the fact that attributes cannot be stacked. 
There is also a 1 tick immunity for entity due to the same problem. Until the attributes are removed, damages are locked.

**Describe alternatives you've considered**
Create a pool of damage per tick and apply them at the end of a tick will make this work.
This method also fix the 1-tick-immunity bug.

**Do you have any code examples, partial implementations, etc**
see datapack linked, and screenshots

**Code**
See datapack linked for example.
Same use and behavior as intended.
Try: /function smithed.damage:test/dmg_pure_start
Try: /function smithed.damage:test/dmg_pure_scheduled_start
[damage-datapack_funkytoc-path.zip](https://github.com/Smithed-MC/Libraries/files/10502276/damage-datapack_funkytoc-path.zip)

![1](https://user-images.githubusercontent.com/29950285/214646753-2128e2f4-6a3e-42dd-8fd7-5b0fd7fb8d21.png)
![2](https://user-images.githubusercontent.com/29950285/214646758-cb1d8d63-0f71-45f7-a8fa-232d8c20d2e2.png)
![3](https://user-images.githubusercontent.com/29950285/214646761-8fe31915-d1d6-43a0-9bc8-7a3221d74ba5.png)
![4](https://user-images.githubusercontent.com/29950285/214646764-efcb9572-5884-431d-aa27-618889479372.png)

**Comment by FunkyToc** [comment]
Replace @a with @e in the tick function to fix the entity side.

**Comment by RitikShah** [comment]
Closing since `/damage` is a command. `smithed.damage` will not make it to 1.20.
